baseURL: "https://ames.world/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Ian Ames - I help multidisciplinary teams deliver services in a user centred way.
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    disableJS: true
    disableCSS: true
    minifyOutput: false

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Search
                  url: search/
                  weight: 5
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories
                  weight: 15
                - name: CV
                  url: /CV/
                  weight: 20


#search engine
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Ian Ames
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    disableThemeToggle: false
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: false
    comments: false
    #images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "../public/home/ian_ames.jpg"
        imageTitle: Ian Ames
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Hi I'm Ian Ames"
        Content: 
            <p>I have over 20 years experience delivering projects to a range of Government organisations including 
            the Ministry of Justice, Cabinet Office, DEFRA, Dept for Culture Media and Sport, NHS Digital and TechUK.</p>

            <p>I have experience of a number of agile practices such as Scrum, Kanban, Cynefin, Lean and DevOps. 
            In recent years I have tended to specialise in the early phases of a service lifecycle. 
            I enjoy working in small teams; being at the intersection of product, tech, and UX; and taking the seed 
            of an idea and shaping it to achievable outcomes.</p>

            <p>I have experience of leading co-located, distributed and fully remote teams. Clear communication and a shared
             understanding of goals is key, regardless of where your team is. I work hard to ensure teams are pulling in 
             the same direction and are focused on the project outcomes.</p>

           
    socialIcons:
        - name: bluesky
          url: "https://bsky.app/profile/ames.world"
        - name: linkedin
          url: "https://www.linkedin.com/in/ianames/"
        - name: email
          url: "ian@discover-deliver.co.uk"
        - name: github
          url: "https://github.com/skipster2k2"
        - name: RsS
          url: "index.xml"

    editPost:
        URL: "https://github.com/skipster2k2/ames-blog/tree/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true