theme = "bento"
languageCode = "en-us"
baseurl = "https://ames.world"
title = "Ames World"

author = "Ian Ames"
copyright = "MIT"

[taxonomies]
category = "categories"
tag = "tags"

# Better code higlighting
# via https://discourse.gohugo.io/t/pygmentscodefences-how-to-choose-themes/3842/3
pygmentsCodefences = true
pygmentsStyle = "vs"

# Integrations
googleAnalytics = "UA-XXXXXX-YY"
disqusShortname = "bento-hugo-theme"

# Hightlight theme
[markup.highlight]
  style = "github"

# Allow HTML rendering inside markdown
[markup.goldmark.renderer]
  unsafe = true

[params]
  # Show intro in the home page (with headline and description)
  intro = true
  headline = "Hi I'm Ian Ames"
  description = "Here's my thoughts on agile, history, software delivery, bikes, product management, sheds, and anything else that is on my mind."

  # Copyright note in the footer
  copyright = "Copyright © 2020 Ian Ames"

  # Image in the homepage. You can setup a different image for social media
  cover = "images/team.jpg"
  ogImage = "images/og_image.jpg"

  # Social media usernames
  github = "https://github.com/skipster2k2"
  twitter = "https://twitter.com/IanAmes"
  linkedin = "https://linkedin.com/in/ianames/"

  # Avatar (shown in the homepage)
  avatar = "images/ian_ames.jpg"
  # Bio is shown in the end of posts
  authorBio = "Thanks for reading!"

# If you want to use fathom (https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#   siteID = "XXXXX"
# Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#  serverURL = "analytics.example.com"

# If you want to use umami (https://umami.is/) for analytics, add this section
#[params.umami]
#  siteID = "XXXXX"
#  trackerScript = "//umami.example.com/umami.js"

# Items in the top menu
[menu]
  [[menu.main]]
      name = "About"
      url = "/about"
      weight = 1

  [[menu.main]]
      name = "User Manual"
      url = "/user-manual-of-me"
      weight = 1

